### ISSUE TITLE
go-cmdtest does not work on Windows anymore

### ISSUE THREAD

**Issue by vangent** [google/go-cmdtest#12]
https://github.com/google/go-cmdtest/pull/4
  started using github.com/google/renameio to rename files.

https://github.com/google/renameio#windows-support indicates that renameio doesn't work on Windows.

Therefore, that commit breaks any use of this package on Windows.

@jba 
@gbrlsnchs 

Thoughts?

**Comment by jba** [comment]
We should use build tags so Windows uses the original rename code.

**Comment by gbrlsnchs** [comment]
> We should use build tags so Windows uses the original rename code.

I agree with this solution.

**Comment by jba** [comment]
I can do the work but have no way to test on Windows. Robert, can you verify the fix?

**Comment by jba** [comment]
(I'm assuming you're reporting it because you ran into it.)

**Comment by vangent** [comment]
I ran into this because gocloud uses go-cmdtest, and includes a Windows run in its Travis configuration. So, I can verify a committed fix I think, but not easily a PR.

**Comment by vangent** [comment]
Fixed by #13.
